// src/ai/flows/curriculum-creator.ts
'use server';

/**
 * @fileOverview Curriculum Creator AI agent.
 *
 * - createCurriculum - A function that creates a curriculum outline based on subject matter and learning objectives.
 * - CreateCurriculumInput - The input type for the createCurriculum function.
 * - CreateCurriculumOutput - The return type for the createCurriculum function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CreateCurriculumInputSchema = z.object({
  subject: z.string().describe('The subject matter for the curriculum.'),
  learningObjectives: z.string().describe('The learning objectives for the curriculum.'),
});

export type CreateCurriculumInput = z.infer<typeof CreateCurriculumInputSchema>;

const CreateCurriculumOutputSchema = z.object({
  curriculumOutline: z.string().describe('The curriculum outline generated by the AI.'),
});

export type CreateCurriculumOutput = z.infer<typeof CreateCurriculumOutputSchema>;

export async function createCurriculum(input: CreateCurriculumInput): Promise<CreateCurriculumOutput> {
  return createCurriculumFlow(input);
}

const prompt = ai.definePrompt({
  name: 'createCurriculumPrompt',
  input: {schema: CreateCurriculumInputSchema},
  output: {schema: CreateCurriculumOutputSchema},
  prompt: `You are an expert curriculum designer. Please create a curriculum outline based on the following subject and learning objectives:

Subject: {{{subject}}}
Learning Objectives: {{{learningObjectives}}}

Curriculum Outline:`,
});

const createCurriculumFlow = ai.defineFlow(
  {
    name: 'createCurriculumFlow',
    inputSchema: CreateCurriculumInputSchema,
    outputSchema: CreateCurriculumOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
